// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PustokApp.Data;

#nullable disable

namespace PustokApp.Data.Migrations
{
    [DbContext(typeof(PustokAppDbContext))]
    partial class PustokAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PustokApp.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            FullName = "George Orwell",
                            ImageUrl = "assets/image/products/product-1.jpg"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            FullName = "Jane Austen",
                            ImageUrl = "assets/image/products/product-2.jpg"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            FullName = "Mark Twain",
                            ImageUrl = "assets/image/products/product-3.jpg"
                        });
                });

            modelBuilder.Entity("PustokApp.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("HoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AuthorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = 1001,
                            Description = "Dystopian social science fiction novel and cautionary tale.",
                            DiscountPercentage = 10,
                            HoverImageUrl = "assets/image/products/product-2.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "assets/image/products/product-1.jpg",
                            Name = "1984",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AuthorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = 1002,
                            Description = "A romantic novel of manners written by Jane Austen.",
                            DiscountPercentage = 0,
                            HoverImageUrl = "assets/image/products/product-4.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "assets/image/products/product-3.jpg",
                            Name = "Pride and Prejudice",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = 1003,
                            Description = "A novel by Mark Twain, first published in 1884.",
                            DiscountPercentage = 5,
                            HoverImageUrl = "assets/image/products/product-6.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "assets/image/products/product-5.jpg",
                            Name = "Adventures of Huckleberry Finn",
                            Price = 12.50m
                        });
                });

            modelBuilder.Entity("PustokApp.Models.BookImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImage");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-aaaaaaaa0001"),
                            BookId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Image = "assets/image/products/product-1.jpg"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-aaaaaaaa0002"),
                            BookId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image = "assets/image/products/product-3.jpg"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-aaaaaaaa0003"),
                            BookId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Image = "assets/image/products/product-5.jpg"
                        });
                });

            modelBuilder.Entity("PustokApp.Models.BookTag", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TagId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Id = new Guid("bbbbbbbb-0000-0000-0000-bbbbbbbb0001")
                        },
                        new
                        {
                            BookId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TagId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("bbbbbbbb-0000-0000-0000-bbbbbbbb0002")
                        },
                        new
                        {
                            BookId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TagId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Id = new Guid("bbbbbbbb-0000-0000-0000-bbbbbbbb0003")
                        });
                });

            modelBuilder.Entity("PustokApp.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PustokApp.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("PustokApp.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Classic"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("PustokApp.Models.Book", b =>
                {
                    b.HasOne("PustokApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PustokApp.Models.BookImage", b =>
                {
                    b.HasOne("PustokApp.Models.Book", "Book")
                        .WithMany("BookImages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("PustokApp.Models.BookTag", b =>
                {
                    b.HasOne("PustokApp.Models.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PustokApp.Models.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PustokApp.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("PustokApp.Models.Book", b =>
                {
                    b.Navigation("BookImages");

                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("PustokApp.Models.Tag", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
